name: Ruby

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.0
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Build and test with minitest
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails test
        
    - name: Pronto Ruby
      uses: AdWerx/pronto-ruby@v2.5

